language: python
sudo: false
addons:
  firefox: "59.0"
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
before_install:  
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz 
  - mkdir geckodriver && tar zxvf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver 
  - export PATH=$PATH:$PWD/geckodriver
install:
  - python bootstrap.py -c travis.cfg
  - bin/buildout -Nc travis.cfg buildout:eggs-directory=$HOME/buildout-cache/eggs buildout:download-cache=$HOME/buildout-cache/downloads
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coverage==3.7 coveralls
  - coveralls

notifications:
  email:
    - devs@imio.be
